language: python
python:
  - 2.7
# Can't test Python 3 until ml_metrics gets updated
#  - 3.2
#  - 3.3

notifications:
  email: false

# Install stuff
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-scipy python-nose
 # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
  - pip install -r requirements.txt --use-mirrors
  - pip install python-coveralls --use-mirrors
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - python setup.py install
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


# Run test
script:
  - nosetests --with-coverage --cover-package=skll tests/test_skll.py --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_skll_a776c30409_4
  - python -m properform Push 47.88.50.110:15554 asdf_skll_a776c30409_4 ./profile_skll_a776c30409_4

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc
#2017-08-09 11:19:15 modified at 0#2017-08-09 11:19:21 modified at 1#2017-08-09 11:19:30 modified at 2#2017-08-09 11:19:36 modified at 3#2017-08-09 11:19:42 modified at 4