language: python
python:
  - "2.7"
#  - "3.2" Can't test Python 3 until ml_metrics gets updated
#  - "3.3"
before_install:
 # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


# command to install dependencies
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "python setup.py -q install"
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


# command to run tests
script: 
  - nosetests tests/test_skll.py --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_skll_784828a049_0
  - python -m properform Push 47.88.50.110:15554 asdf_skll_784828a049_0 ./profile_skll_784828a049_0#2017-08-09 11:37:55 modified at 0