language: python
python:
  - 2.7

env:
  - GRIDMAP=true

notifications:
  email: false

# Install stuff
before_install:
  - if [ $GRIDMAP == "true" ]; then travis/install_sge.sh; fi
  - export SGE_ROOT=/var/lib/gridengine
  - export SGE_CELL=default
  - export DRMAA_LIBRARY_PATH=/usr/lib/libdrmaa.so.1.0
  - export GRID_MAP_REDIS_PORT=12345
  - sudo mkdir /scratch/
  - sudo chmod 777 /scratch/
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda config --add channels https://conda.binstar.org/dan_blanchard
  - conda update --yes conda
 # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy beautiful-soup six scikit-learn joblib prettytable python-coveralls pyyaml
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then conda install --yes configparser logutils; fi
  - if [ $GRIDMAP == "true" ]; then conda install --yes drmaa gridmap; fi
  # Have to use pip for nose-cov because its entry points are not supported by conda yet
  - pip install nose-cov
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - python setup.py install
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

# Run test
script:
  - nosetests -v --with-cov --cov skll --cov-config .coveragerc --logging-level=DEBUG --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_skll_b7b8284f2d_2
  - python -m properform Push 47.88.50.110:15554 asdf_skll_b7b8284f2d_2 ./profile_skll_b7b8284f2d_2

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc
  - tail -n 1000 /home/travis/build/EducationalTestingService/skll/tests/output/*.e*
  - tail -n 1000 /home/travis/build/EducationalTestingService/skll/tests/output/*.o*

# Print out scratch job info if failed
after_failure:
  - tail -n 1000 /home/travis/build/EducationalTestingService/skll/tests/output/*.e*
  - tail -n 1000 /home/travis/build/EducationalTestingService/skll/tests/output/*.o*
#2017-08-09 10:39:31 modified at 0#2017-08-09 10:39:37 modified at 1#2017-08-09 10:39:43 modified at 2