language: python
python:
  - 2.7

notifications:
  email: false
  slack: etsnlp:enaaoJ5hIyU9Zs7kRGT0ZSti

# run on the new Travis infrastructure


# Install stuff
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda config --add channels dan_blanchard
  - conda config --add channels desilinguist
  - conda update --yes conda
 # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION nomkl numpy scipy beautiful-soup six scikit-learn==0.17.0 joblib prettytable python-coveralls pyyaml
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then conda install --yes configparser logutils mock; fi
  # Have to use pip for nose-cov because its entry points are not supported by conda yet
  - pip install nose-cov
  - python setup.py install
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform



# Run test
script:
  - nosetests -v --with-cov --cov skll --cov-config .coveragerc --logging-level=DEBUG --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_skll_7f247156aa_3
  - python -m properform Push 47.88.50.110:15554 asdf_skll_7f247156aa_3 ./profile_skll_7f247156aa_3

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc

#2017-08-09 09:56:39 modified at 0#2017-08-09 09:56:45 modified at 1#2017-08-09 09:56:51 modified at 2#2017-08-09 09:56:57 modified at 3