language: python
python:
  - 2.7


notifications:
  email: false

# Install stuff
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-scipy python-nose python3-scipy python3-nose
 # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq



install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then pip install --use-mirrors configparser; fi
  - pip install -r requirements.txt --use-mirrors
  - pip install python-coveralls --use-mirrors
  - pip install nose-cov --use-mirrors
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - python setup.py install
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


# Run test
script:
  - nosetests --with-cov --cov skll --cov-config .coveragerc tests/test_skll.py --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_skll_eacd9e424c_4
  - python -m properform Push 47.88.50.110:15554 asdf_skll_eacd9e424c_4 ./profile_skll_eacd9e424c_4



# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc
#2017-08-09 11:08:01 modified at 0#2017-08-09 11:08:07 modified at 1#2017-08-09 11:08:13 modified at 2#2017-08-09 11:08:20 modified at 3#2017-08-09 11:08:26 modified at 4