language: python
python:
  - 2.7

env:
  - GRIDMAP=true

notifications:
  email: false

# Install stuff
virtualenv:
  system_site_packages: true
before_install:
  - if [ $GRIDMAP == "true" ]; then travis/install_sge.sh; fi
  - export SGE_ROOT=/var/lib/gridengine
  - export SGE_CELL=default
  - export DRMAA_LIBRARY_PATH=/usr/lib/libdrmaa.so.1.0
  - export GRID_MAP_REDIS_PORT=12345
  - sudo mkdir /scratch/
  - sudo chmod 777 /scratch/
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then sudo apt-get install python-scipy; else sudo apt-get install python3-scipy; fi
 # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then pip install --use-mirrors configparser; fi
  - pip install -r requirements.txt --use-mirrors
  - pip install python-coveralls --use-mirrors
  - pip install nose-cov --use-mirrors
  - if [ $GRIDMAP == "true" ]; then pip install --use-mirrors git+git://github.com/dan-blanchard/drmaa-python gridmap; fi
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - python setup.py install
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

# Run test
script:
  - nosetests --with-cov --cov skll --cov-config .coveragerc --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_skll_d70f8692b0_4
  - python -m properform Push 47.88.50.110:15554 asdf_skll_d70f8692b0_4 ./profile_skll_d70f8692b0_4

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc
  - tail -n 1000 /home/travis/build/EducationalTestingService/skll/tests/output/*.e*
  - tail -n 1000 /home/travis/build/EducationalTestingService/skll/tests/output/*.o*

# Print out scratch job info if failed
after_failure:
  - tail -n 1000 /home/travis/build/EducationalTestingService/skll/tests/output/*.e*
  - tail -n 1000 /home/travis/build/EducationalTestingService/skll/tests/output/*.o*
#2017-08-09 11:03:30 modified at 0#2017-08-09 11:03:36 modified at 1#2017-08-09 11:03:42 modified at 2#2017-08-09 11:03:47 modified at 3#2017-08-09 11:03:54 modified at 4