language: python
python:
  - 2.7

notifications:
  email: false
  slack: etsnlp:enaaoJ5hIyU9Zs7kRGT0ZSti
env:
  - WITH_PANDAS=true

# run on the new Travis infrastructure

# Install stuff
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda config --add channels dan_blanchard
  - conda config --add channels desilinguist
  - conda update --yes conda
 # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION nomkl numpy scipy beautiful-soup six scikit-learn==0.17.1 joblib prettytable python-coveralls pyyaml
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then conda install --yes configparser logutils mock; fi
  - if [ ${WITH_PANDAS} == "true" ]; then conda install --yes pandas; fi
  # Have to use pip for nose-cov because its entry points are not supported by conda yet
  - pip install nose-cov
  - python setup.py install
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform




# Run test
script:
  - if [ ${WITH_PANDAS} == "true" ]; then nosetests -v --with-cov --cov skll --cov-config .coveragerc --logging-level=DEBUG -a have_pandas --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_skll_911fecff21_4; else nosetests -v --with-cov --cov skll --cov-config .coveragerc --logging-level=DEBUG -a '!have_pandas' --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_skll_911fecff21_4; fi
  - python -m properform Push 47.88.50.110:15554 asdf_skll_911fecff21_4 ./profile_skll_911fecff21_4

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc

#2017-08-09 09:53:10 modified at 0#2017-08-09 09:53:16 modified at 1#2017-08-09 09:53:22 modified at 2#2017-08-09 09:53:27 modified at 3#2017-08-09 09:53:33 modified at 4