language: python
python:
  - "2.7"
# Can't test Python 3 until ml_metrics gets updated
#  - "3.2"
#  - "3.3"

notifications:
  email: false

# Install stuff
virtualenv:
    system_site_packages: true
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-scipy python-nose python-sklearn
 # add for profile
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
  - "pip install -r requirements.txt --use-mirrors"
  - "python setup.py install"
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


# Run test
script: 
  - nosetests tests/test_skll.py --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_skll_c3314bbc0b_0
  - python -m properform Push 47.88.50.110:15554 asdf_skll_c3314bbc0b_0 ./profile_skll_c3314bbc0b_0

#2017-08-09 11:36:16 modified at 0